import './globals.css'
import type { Metadata } from 'next'
import { Inter,Roboto } from 'next/font/google'
import Navbar from './Navbar'
import AuthProvider from './auth/Provider'
import Head from 'next/head'
import GoogleAnalytics from '@/app/GoogleAnalytics'

const inter = Inter({ subsets: ['latin'] })
const roboto= Roboto({
  subsets:['latin'],
  weight:'400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph:{
    title:'...',
    description:"..."
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter"> 
      <Head>
        <title>{"next-app"}</title>
        <meta name="description" content={"Lovely website"} />
      </Head>
      <body className={roboto.className}>
        <AuthProvider>
          <Navbar />
          <main className='p-5'>
            {children}
          </main>
        </AuthProvider>
        <GoogleAnalytics trackingId="TAG_ID" />
      </body>
    </html>
  )
}